# Generated by Django 3.1.3 on 2021-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentattempt',
            old_name='Blog',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='paymentattempt',
            old_name='transaction_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='paymentsuccessful',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='paymentsuccessful',
            name='order_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsuccessful',
            name='payment_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
