# Generated by Django 3.1.3 on 2021-01-01 13:13

import apps.blogs.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201206_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blogs.utils.UploadWrapper('thumbnails')),
        ),
    ]
