# Generated by Django 3.1.3 on 2021-01-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210101_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, help_text='In INR', null=True),
        ),
    ]
