# Generated by Django 3.1.3 on 2021-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210101_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type_of',
            field=models.IntegerField(choices=[(1, 'Blog'), (2, 'Projects')], default=1),
        ),
    ]
